//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Book
{
    public Book()
    {
        this.Loans = new HashSet<Loan>();
        this.Users = new HashSet<User>();
    }

    public int ID { get; set; }
    public string BookName { get; set; }
    public string Author { get; set; }
    public string Lent { get; set; }
    public int IDCategory { get; set; }
    public int IDLanguage { get; set; }

    public virtual BookCategory BookCategory { get; set; }
    public virtual BookLanguage BookLanguage { get; set; }
    public virtual BooksDetail BooksDetail { get; set; }
    public virtual ICollection<Loan> Loans { get; set; }
    public virtual ICollection<User> Users { get; set; }
}

public partial class BookCategory
{
    public BookCategory()
    {
        this.Books = new HashSet<Book>();
    }

    public int ID { get; set; }
    public string CategoryName { get; set; }

    public virtual ICollection<Book> Books { get; set; }
}

public partial class BookLanguage
{
    public BookLanguage()
    {
        this.Books = new HashSet<Book>();
    }

    public int ID { get; set; }
    public string LanguageName { get; set; }

    public virtual ICollection<Book> Books { get; set; }
}

public partial class BooksDetail
{
    public int ID { get; set; }
    public byte[] Image { get; set; }
    public string Description { get; set; }
    public string ISBN { get; set; }
    public string Publisher { get; set; }

    public virtual Book Book { get; set; }
}

public partial class Loan
{
    public int ID { get; set; }
    public System.DateTime DateLoan { get; set; }
    public System.DateTime DateReturn { get; set; }
    public Nullable<int> IDBook { get; set; }
    public Nullable<int> IDUser { get; set; }

    public virtual Book Book { get; set; }
    public virtual User User { get; set; }
}

public partial class User
{
    public User()
    {
        this.Loans = new HashSet<Loan>();
        this.Books = new HashSet<Book>();
    }

    public int ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public Nullable<System.DateTime> BirthDate { get; set; }
    public byte[] Avatar { get; set; }
    public Nullable<int> ResetPasswordCode { get; set; }

    public virtual ICollection<Loan> Loans { get; set; }
    public virtual UsersDetail UsersDetail { get; set; }
    public virtual UsersLogin UsersLogin { get; set; }
    public virtual ICollection<Book> Books { get; set; }
}

public partial class UsersDetail
{
    public int ID { get; set; }
    public string Street { get; set; }
    public int StreetNumber { get; set; }
    public string PostalCode { get; set; }
    public string City { get; set; }
    public string Telephone { get; set; }
    public string Country { get; set; }

    public virtual User User { get; set; }
}

public partial class UsersLogin
{
    public int ID { get; set; }
    public string email { get; set; }
    public string PASSWORD { get; set; }
    public string UserRole { get; set; }
    public string Active { get; set; }

    public virtual User User { get; set; }
}
